rtbrick/bdsSnmpAdaptor

- README.md
- docs/configTablesOnBds.json
- docs/modules.rst
- docs/overview.rst
Minor fixes to the docs and re-validated the included JSON config.
> Fix typos and reword some sentences in the doc

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/manager.py
- bdssnmpadaptor/commands/notificator.py
- bdssnmpadaptor/commands/responder.py
- conf/notificator_v3.yml
- conf/responder.yml
- docs/modules.rst
This PR fixes up a couple of assorted issues caused by code reformatting and moving.
> Address layout reshuffle issues

- bdsSnmpAdapterManager.py
- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/notificator.py
- bdssnmpadaptor/commands/responder.py
- bdssnmpadaptor/mapping_functions.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_startup_status_confd.py
- bdssnmpadaptor/mapping_modules/confd_local_system_software_info_confd.py
- bdssnmpadaptor/mapping_modules/ffwd_default_interface_logical.py
- bdssnmpadaptor/mapping_modules/fwdd_global_interface_physical_statistics.py
- bdssnmpadaptor/oidDb.py
- bdssnmpadaptor/predefined_oids.py
Mostly reformatting code, wrapping long lines, optimizing imports
and other small things.
> PEP8 the whole project

- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
> New inteface desc

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/notificator.py
- bdssnmpadaptor/commands/responder.py
- bdssnmpadaptor/log.py
- bdssnmpadaptor/oidDb.py
- bdssnmpadaptor/predefined_oids.py
- conf/notificator.yml
- conf/notificator_v3.yml
- conf/responder.yml
**Better merge this first**
Made log file optional, if not given logging happens to stdout
from where it could be picked up by systemd/journalctl.
> Improve logging here and there

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/notificator.py
- bdssnmpadaptor/commands/responder.py
- bdssnmpadaptor/log.py
- bdssnmpadaptor/oidDb.py
- bdssnmpadaptor/predefined_oids.py
- bdssnmpadaptor/snmp_config.py
- conf/notificator.yml
- conf/notificator_v3.yml
- conf/responder.yml
**Better merge this second**
This PR refactors the way how SNMP engine is configured so that
SNMP responder can respond to some or all of SNMP v1/v2c/v3.
> SNMP responder to support multiple SNMP versions

- bdssnmpadaptor/mapping_modules/confd_global_startup_status_confd.py
> Fix missing import in mapping modules

- sysvinit/onl/bds-snmp-notificator
- sysvinit/onl/bds-snmp-responder
It seems ONL uses SYSV init rather than systemd
> Add SYSV init scripts

- bdssnmpadaptor/commands/notificator.py
- bdssnmpadaptor/commands/responder.py
- sysvinit/onl/bds-snmp-notificator
- sysvinit/onl/bds-snmp-responder
Also, `--configFile` option renamed into `--config` for
uniformity.
> Add $PIDFILE tracking to sysv init scripts

- README.md
Let's enable this repo in Travis CI (see "build" link).
> Update README and add CI badge

- bdssnmpadaptor/commands/responder.py
- bdssnmpadaptor/oidDb.py
Expensive `eval` replaced with class instantiation
> Change SNMP managed object instantiation

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/notificator.py
- bdssnmpadaptor/commands/responder.py
- bdssnmpadaptor/log.py
- bdssnmpadaptor/oidDb.py
- bdssnmpadaptor/snmp_config.py
Name logging handlers after owning classes, retain loggers' hierarchy.
> 02 - Refactor logging

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/responder.py
Mostly more forgiving to missing REST API data, malformed
mapping functions configuration.
> 01 - Make SNMP command responder more resilient

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/notificator.py
- bdssnmpadaptor/commands/responder.py
- tests/unit/test_access.py
Also fixed a regression in unit test and converted notification originator to fstrings for consistency.
> 02 - Resilient notification originator

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/notificator.py
- bdssnmpadaptor/commands/responder.py
- bdssnmpadaptor/config.py
- bdssnmpadaptor/mapping_functions.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/confd_global_startup_status_confd.py
- bdssnmpadaptor/mapping_modules/confd_local_system_software_info_confd.py
- bdssnmpadaptor/mapping_modules/ffwd_default_interface_logical.py
- bdssnmpadaptor/mapping_modules/fwdd_global_interface_physical_statistics.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
- bdssnmpadaptor/oidDb.py
- bdssnmpadaptor/predefined_oids.py
- tests/startuptime.py
- tests/unit/test_access.py
This is a large but simple PR - it unifies quotes to be single unless it's a docstring.
> 03 - PEP8 quotes

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/notificator.py
- bdssnmpadaptor/commands/responder.py
- bdssnmpadaptor/config.py
- bdssnmpadaptor/daemon.py
- bdssnmpadaptor/mapping_functions.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/confd_global_startup_status_confd.py
- bdssnmpadaptor/mapping_modules/confd_local_system_software_info_confd.py
- bdssnmpadaptor/mapping_modules/ffwd_default_interface_logical.py
- bdssnmpadaptor/mapping_modules/fwdd_global_interface_physical_statistics.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
- bdssnmpadaptor/oidDb.py
- bdssnmpadaptor/predefined_oids.py
- setup.py
- tests/integration/testBdsLoggingToSnmpNotification.py
- tests/integration/testBdsLoggingToSnmpNotification_async.py
- tests/startuptime.py
- tests/unit/test_access.py
Also, officially require Python 3.6+
> 04 - Unify on f-strings

- bdssnmpadaptor/access.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/confd_global_startup_status_confd.py
- bdssnmpadaptor/mapping_modules/confd_local_system_software_info_confd.py
- bdssnmpadaptor/mapping_modules/ffwd_default_interface_logical.py
- bdssnmpadaptor/mapping_modules/fwdd_global_interface_physical_statistics.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
- bdssnmpadaptor/mapping_modules/predefined_oids.py
- bdssnmpadaptor/oidDb.py
- tests/unit/mapping_modules/test_confd_global_interface_container.py
- tests/unit/mapping_modules/test_confd_global_interface_physical.py
- tests/unit/mapping_modules/test_confd_global_startup_status_confd.py
- tests/unit/mapping_modules/test_confd_local_system_software_info_confd.py
- tests/unit/mapping_modules/test_ffwd_default_interface_logical.py
- tests/unit/mapping_modules/test_fwdd_global_interface_physical_statistics.py
- tests/unit/mapping_modules/test_lldpd_global_lldp_intf_status.py
- tests/unit/mapping_modules/test_predefined_oids.py
- tests/unit/test_access.py
- tests/unit/test_oiddb.py
This is done in preparation to documenting OID DB population modules.
> 02 - Rearrange OID DB methods signatures

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/adaptor.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/confd_global_startup_status_confd.py
- bdssnmpadaptor/mapping_modules/confd_local_system_software_info_confd.py
- bdssnmpadaptor/mapping_modules/ffwd_default_interface_logical.py
- bdssnmpadaptor/mapping_modules/fwdd_global_interface_physical_statistics.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
- bdssnmpadaptor/mapping_modules/predefined_oids.py
- bdssnmpadaptor/oidDb.py
- tests/unit/commands/test_adaptor.py
- tests/unit/mapping_modules/test_confd_global_interface_container.py
- tests/unit/mapping_modules/test_confd_global_interface_physical.py
- tests/unit/mapping_modules/test_confd_global_startup_status_confd.py
- tests/unit/mapping_modules/test_confd_local_system_software_info_confd.py
- tests/unit/mapping_modules/test_ffwd_default_interface_logical.py
- tests/unit/mapping_modules/test_fwdd_global_interface_physical_statistics.py
- tests/unit/mapping_modules/test_lldpd_global_lldp_intf_status.py
- tests/unit/mapping_modules/test_predefined_oids.py
- tests/unit/test_access.py
- tests/unit/test_oiddb.py
This change is done in preparation to adding stale data expiration feature.
> 04 - Simplify access module

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/adaptor.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/confd_global_startup_status_confd.py
- bdssnmpadaptor/mapping_modules/confd_local_system_software_info_confd.py
- bdssnmpadaptor/mapping_modules/ffwd_default_interface_logical.py
- bdssnmpadaptor/mapping_modules/fwdd_global_interface_physical_statistics.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
- bdssnmpadaptor/mapping_modules/predefined_oids.py
- bdssnmpadaptor/oidDb.py
- bdssnmpadaptor/oid_db.py
- tests/unit/commands/test_adaptor.py
- tests/unit/mapping_modules/test_confd_global_interface_container.py
- tests/unit/mapping_modules/test_confd_global_interface_physical.py
- tests/unit/mapping_modules/test_confd_global_startup_status_confd.py
- tests/unit/mapping_modules/test_confd_local_system_software_info_confd.py
- tests/unit/mapping_modules/test_ffwd_default_interface_logical.py
- tests/unit/mapping_modules/test_fwdd_global_interface_physical_statistics.py
- tests/unit/mapping_modules/test_lldpd_global_lldp_intf_status.py
- tests/unit/mapping_modules/test_predefined_oids.py
- tests/unit/test_access.py
- tests/unit/test_oiddb.py
This change refactors and completes BDS objects sequences tracking when it comes to updating OID DB.
> 06 - Ensure OID DB updates only when necessary

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/adaptor.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/confd_global_startup_status_confd.py
- bdssnmpadaptor/mapping_modules/confd_local_system_software_info_confd.py
- bdssnmpadaptor/mapping_modules/ffwd_default_interface_logical.py
- bdssnmpadaptor/mapping_modules/fwdd_global_interface_physical_statistics.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
- bdssnmpadaptor/mapping_modules/predefined_oids.py
- bdssnmpadaptor/oidDb.py
- bdssnmpadaptor/oid_db.py
- tests/unit/commands/test_adaptor.py
- tests/unit/mapping_modules/test_confd_global_interface_container.py
- tests/unit/mapping_modules/test_confd_global_interface_physical.py
- tests/unit/mapping_modules/test_confd_global_startup_status_confd.py
- tests/unit/mapping_modules/test_confd_local_system_software_info_confd.py
- tests/unit/mapping_modules/test_ffwd_default_interface_logical.py
- tests/unit/mapping_modules/test_fwdd_global_interface_physical_statistics.py
- tests/unit/mapping_modules/test_lldpd_global_lldp_intf_status.py
- tests/unit/mapping_modules/test_predefined_oids.py
- tests/unit/test_access.py
- tests/unit/test_oiddb.py
Adds unit tests for OID DB `.add` method, in particular targeting stale entries expiration mechanics.
> 08 - Add more OID DB unit tests

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/adaptor.py
- bdssnmpadaptor/mib_controller.py
- bdssnmpadaptor/oid_db.py
- bdssnmpadaptor/rest_server.py
- bdssnmpadaptor/snmp_notificator.py
- bdssnmpadaptor/snmp_responder.py
- tests/unit/commands/test_adaptor.py
- tests/unit/mapping_modules/test_confd_global_interface_container.py
- tests/unit/mapping_modules/test_confd_global_interface_physical.py
- tests/unit/mapping_modules/test_confd_global_startup_status_confd.py
- tests/unit/mapping_modules/test_confd_local_system_software_info_confd.py
- tests/unit/mapping_modules/test_ffwd_default_interface_logical.py
- tests/unit/mapping_modules/test_fwdd_global_interface_physical_statistics.py
- tests/unit/mapping_modules/test_lldpd_global_lldp_intf_status.py
- tests/unit/mapping_modules/test_predefined_oids.py
- tests/unit/test_access.py
- tests/unit/test_mib_controller.py
- tests/unit/test_oiddb.py
- tests/unit/test_rest_server.py
- tests/unit/test_snmp_notificator.py
- tests/unit/test_snmp_responder.py
This change removes unused code in the BDS access module, documents and renames some variables for better clarify.
> 10 -  Simplify access module

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/adaptor.py
- bdssnmpadaptor/mapping_modules/predefined_oids.py
- bdssnmpadaptor/mib_controller.py
- bdssnmpadaptor/oid_db.py
- bdssnmpadaptor/rest_server.py
- bdssnmpadaptor/snmp_notificator.py
- bdssnmpadaptor/snmp_responder.py
- conf/bds-snmp-adaptor.yml
- docs/installation.rst
- tests/unit/commands/test_adaptor.py
- tests/unit/mapping_modules/test_confd_global_interface_container.py
- tests/unit/mapping_modules/test_confd_global_interface_physical.py
- tests/unit/mapping_modules/test_confd_global_startup_status_confd.py
- tests/unit/mapping_modules/test_confd_local_system_software_info_confd.py
- tests/unit/mapping_modules/test_ffwd_default_interface_logical.py
- tests/unit/mapping_modules/test_fwdd_global_interface_physical_statistics.py
- tests/unit/mapping_modules/test_lldpd_global_lldp_intf_status.py
- tests/unit/mapping_modules/test_predefined_oids.py
- tests/unit/test_access.py
- tests/unit/test_mib_controller.py
- tests/unit/test_oiddb.py
- tests/unit/test_rest_server.py
- tests/unit/test_snmp_notificator.py
- tests/unit/test_snmp_responder.py
Also moves Python code compilation to OID DB for generality.
> 12 - Add unit tests against predefined OID code snippets

- bdssnmpadaptor/oid_db.py
- bdssnmpadaptor/snmp_notificator.py
- systemd/ubuntu/bds-snmp-adaptor.service
- sysvinit/generic/bds-snmp-adaptor
- sysvinit/onl/bds-snmp-adaptor
- tests/unit/test_snmp_notificator.py
Fix minor issues accumulated over recent patches. Most importantly, this fixes wrong TRAP OID.
> 01 - Fix wrong TRAP OID and other minor issues

- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/confd_local_system_software_info_confd.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
- tests/unit/mapping_modules/test_confd_local_system_software_info_confd.py
This change updates ifLastChange SNMP table column along with the rest of table columns to ensure it won't get expired on inactivity.
> 01 - Update ifLastChange to ensure it's not expiring

- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/confd_local_system_software_info_confd.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
- bdssnmpadaptor/mapping_modules/predefined_oids.py
- bdssnmpadaptor/oid_db.py
- tests/unit/mapping_modules/test_confd_local_system_software_info_confd.py
This change makes OID DB expiring OIDs on per-module basis. This preserves OIDs for a module which is updated less frequently then others.
> 02 -  Fix OID DB premature expiration

- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/ffwd_default_interface_logical.py
- bdssnmpadaptor/mapping_modules/fwdd_global_interface_physical_statistics.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
Assuming that the ordering of `{"objects": {"sequence": N}}` is stable.
> 01 - Do not update ifTable for interfaces that do not change

- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/ffwd_default_interface_logical.py
- bdssnmpadaptor/mapping_modules/fwdd_global_interface_physical_statistics.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
- bdssnmpadaptor/oid_db.py
- tests/unit/mapping_modules/test_confd_global_interface_container.py
- tests/unit/mapping_modules/test_confd_global_interface_physical.py
- tests/unit/mapping_modules/test_lldpd_global_lldp_intf_status.py
The goal or "refresh" is to indicate to the OID DB that this entry is still actual and should not be expired.
> 02 - Add "refresh" operation to OID DB

- bdssnmpadaptor/access.py
- bdssnmpadaptor/commands/__init__.py
- bdssnmpadaptor/commands/adaptor.py
- bdssnmpadaptor/commands/graylogTestClient.py
- bdssnmpadaptor/config.py
- bdssnmpadaptor/daemon.py
- bdssnmpadaptor/error.py
- bdssnmpadaptor/log.py
- bdssnmpadaptor/mapping_functions.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/confd_global_startup_status_confd.py
- bdssnmpadaptor/mapping_modules/confd_local_system_software_info_confd.py
- bdssnmpadaptor/mapping_modules/ffwd_default_interface_logical.py
- bdssnmpadaptor/mapping_modules/fwdd_global_interface_physical_statistics.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
- bdssnmpadaptor/mapping_modules/predefined_oids.py
- bdssnmpadaptor/mib_controller.py
- bdssnmpadaptor/oid_db.py
- bdssnmpadaptor/rest_server.py
- bdssnmpadaptor/snmp_config.py
- bdssnmpadaptor/snmp_notificator.py
- bdssnmpadaptor/snmp_responder.py
- requirements.txt
- setup.py
- tests/integration/testBdsLoggingToSnmpNotification_async.py
- tests/unit/test_access.py
- tests/unit/test_rest_server.py
This change replaces newer Python syntax and pins dependencies in effort to provide Python 3.4+ compatibility.
> 02 - Add Python 3.4 compatibility

- bdssnmpadaptor/mapping_modules/confd_global_interface_container.py
- bdssnmpadaptor/mapping_modules/confd_global_interface_physical.py
- bdssnmpadaptor/mapping_modules/ffwd_default_interface_logical.py
- bdssnmpadaptor/mapping_modules/fwdd_global_interface_physical_statistics.py
- bdssnmpadaptor/mapping_modules/lldpd_global_lldp_intf_status.py
- tests/unit/mapping_modules/test_ffwd_default_interface_logical.py
- tests/unit/mapping_modules/test_fwdd_global_interface_physical_statistics.py
It turns out that initial `ifLastChange` value is not zero as it should be.
Also added missing `ifTable` time-stamping in the emerging mapping modules.
> 01 - Fix initial `ifLastChange` value assignment

- bdssnmpadaptor/mib_controller.py
- bdssnmpadaptor/oid_db.py
- bdssnmpadaptor/rest_server.py
Adds more docstrings to some of the methods documenting their behaviour and call signature.
> 01 - Add docstrings

- bdssnmpadaptor/mib_controller.py
- bdssnmpadaptor/oid_db.py
- bdssnmpadaptor/rest_server.py
- bdssnmpadaptor/snmp_config.py
Second portion of docstrings explaining methods behavior and call signature.
> 02 - Add docstrings

- bdssnmpadaptor/snmp_notificator.py
- bdssnmpadaptor/snmp_responder.py
- conf/bds-snmp-adaptor.yml
This is the final patch in the chain adding docstrings to all the methods documenting their behaviour and call signature.
> 03 - Add docstrings

- bdssnmpadaptor/rest_server.py
- tests/unit/test_rest_server.py
Handle REST API request errors, adds logging and unit tests on error handling. Require `PUT` or `POST` methods, do not return request headers in response.
> 01 - Harden REST server against malformed input

- mibs/RTBRICK-SYSLOG-MIB.txt
Hi Stefan,
as discussed here is the fixed trap definition.
> Added varbind-objects to trap rtbrickSyslogTrap
